"use client";

import { useState, type ReactElement } from "react";

import type { TraceResult } from "@kadenatrace/shared";

import { truncateAddress } from "../lib/investigation";

interface PDFExportProps {
  trace: TraceResult;
  summary: {
    summaryLine: string;
    conclusion: string;
    overallRisk: string;
    overallScore: number;
    confidencePct: number;
    whySuspicious: string;
    typeLabel: string;
  };
  onClose: () => void;
}

export function PDFExportModal({ trace, summary, onClose }: PDFExportProps): ReactElement {
  const handlePrint = (): void => {
    window.print();
  };

  return (
    <div className="pdf-export-container" style={{ display: "none" }}>
      <div id="pdf-content" style={{ padding: "40px", background: "white", color: "#1a1a1a" }}>
        <h1 style={{ fontSize: "24px", fontWeight: 700, marginBottom: "8px" }}>
          KadenaTrace Investigation Report
        </h1>
        <p style={{ color: "#666", marginBottom: "24px", fontSize: "14px" }}>
          Trace ID: {trace.traceId} | Generated: {new Date().toLocaleString()}
        </p>

        <section style={{ marginBottom: "32px" }}>
          <h2 style={{ fontSize: "18px", fontWeight: 600, marginBottom: "12px" }}>Investigation Conclusion</h2>
          <p style={{ fontSize: "16px", fontWeight: 500, marginBottom: "8px" }}>{summary.summaryLine}</p>
          <p style={{ fontSize: "14px", color: "#444", lineHeight: 1.6 }}>{summary.conclusion}</p>
        </section>

        <div style={{ display: "flex", gap: "16px", marginBottom: "32px" }}>
          <div style={{ padding: "16px", background: "#f5f5f5", borderRadius: "8px", textAlign: "center" }}>
            <div style={{ fontSize: "24px", fontWeight: 700 }}>{summary.overallScore}%</div>
            <div style={{ fontSize: "12px", color: "#666" }}>Risk Score</div>
          </div>
          <div style={{ padding: "16px", background: "#f5f5f5", borderRadius: "8px", textAlign: "center" }}>
            <div style={{ fontSize: "24px", fontWeight: 700 }}>{summary.confidencePct}%</div>
            <div style={{ fontSize: "12px", color: "#666" }}>Confidence</div>
          </div>
          <div style={{ padding: "16px", background: "#f5f5f5", borderRadius: "8px", textAlign: "center" }}>
            <div style={{ fontSize: "24px", fontWeight: 700 }}>{summary.typeLabel}</div>
            <div style={{ fontSize: "12px", color: "#666" }}>Type</div>
          </div>
        </div>

        <section style={{ marginBottom: "32px" }}>
          <h2 style={{ fontSize: "18px", fontWeight: 600, marginBottom: "12px" }}>Risk Signals</h2>
          <p style={{ fontSize: "14px", lineHeight: 1.6 }}>{summary.whySuspicious}</p>
        </section>

        <section style={{ marginBottom: "32px" }}>
          <h2 style={{ fontSize: "18px", fontWeight: 600, marginBottom: "12px" }}>Transaction Summary</h2>
          <table style={{ width: "100%", fontSize: "14px", borderCollapse: "collapse" }}>
            <tbody>
              <tr>
                <td style={{ padding: "8px 0", color: "#666" }}>Total Nodes</td>
                <td style={{ padding: "8px 0", textAlign: "right" }}>{trace.graph.nodes.length}</td>
              </tr>
              <tr>
                <td style={{ padding: "8px 0", color: "#666" }}>Total Edges</td>
                <td style={{ padding: "8px 0", textAlign: "right" }}>{trace.graph.edges.length}</td>
              </tr>
              <tr>
                <td style={{ padding: "8px 0", color: "#666" }}>Seed Wallet</td>
                <td style={{ padding: "8px 0", textAlign: "right", fontFamily: "monospace", fontSize: "12px" }}>
                  {truncateAddress(trace.seed.seedValue)}
                </td>
              </tr>
            </tbody>
          </table>
        </section>

        <section>
          <h2 style={{ fontSize: "18px", fontWeight: 600, marginBottom: "12px" }}>Risk Findings</h2>
          {trace.findings.length === 0 ? (
            <p style={{ fontSize: "14px", color: "#666" }}>No risk findings detected.</p>
          ) : (
            <ul style={{ fontSize: "14px", paddingLeft: "20px", lineHeight: 1.8 }}>
              {trace.findings.map((finding, i) => (
                <li key={i}>
                  <strong>{finding.severity.toUpperCase()}</strong>: {finding.explanation}
                </li>
              ))}
            </ul>
          )}
        </section>

        <footer style={{ marginTop: "48px", paddingTop: "24px", borderTop: "1px solid #eee", fontSize: "12px", color: "#888" }}>
          <p>This report was generated by KadenaTrace. The trace hash can be independently verified on Kadena blockchain.</p>
          <p style={{ marginTop: "8px" }}>Trace Hash: {trace.traceHash}</p>
        </footer>
      </div>
    </div>
  );
}

interface ExportButtonProps {
  trace: TraceResult;
  summary: {
    summaryLine: string;
    conclusion: string;
    overallRisk: string;
    overallScore: number;
    confidencePct: number;
    whySuspicious: string;
    typeLabel: string;
  };
}

export function ExportReportButton({ trace, summary }: ExportButtonProps): ReactElement {
  const [showModal, setShowModal] = useState(false);

  return (
    <>
      <button className="ghost-button" onClick={() => setShowModal(true)}>
        📄 Export Report
      </button>

      {showModal && (
        <div
          style={{
            position: "fixed",
            inset: 0,
            zIndex: 1000,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            padding: "24px"
          }}
          onClick={() => setShowModal(false)}
        >
          <div
            style={{
              position: "absolute",
              inset: 0,
              background: "rgba(0, 0, 0, 0.7)",
              backdropFilter: "blur(4px)"
            }}
          />

          <div
            className="panel"
            style={{
              position: "relative",
              maxWidth: "420px",
              width: "100%",
              padding: "32px"
            }}
            onClick={(e) => e.stopPropagation()}
          >
            <h2 className="section-title" style={{ fontSize: "1.25rem", marginBottom: "8px" }}>
              Export Investigation Report
            </h2>

            <p className="muted" style={{ marginBottom: "24px", fontSize: "14px", lineHeight: 1.6 }}>
              Generate a printable PDF report containing the investigation summary, risk findings, and transaction timeline.
            </p>

            <div style={{ display: "flex", gap: "12px", flexWrap: "wrap" }}>
              <button className="button" onClick={() => window.print()}>
                📄 Print / Save as PDF
              </button>

              <button className="ghost-button" onClick={() => setShowModal(false)}>
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}